name: Test & Deploy Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Build image and Run Test
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t singhpankaj23/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true singhpankaj23/docker-react npm run test
