name: Test & Deploy Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t singhpankaj23/docker-react -f Dockerfile.dev .
      - name: Run Test
        run: docker run -e CI=true singhpankaj23/docker-react npm run test
